name: CI
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install requirements
        run: nix profile install .#terraform-ci

      - name: Terraform format
        run: tofu fmt -check -recursive .

      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          secrets-json: ${{ toJson(secrets) }}
          tfstate-endpoint: ${{ secrets.TF_STATE_ENDPOINT }}
          tfstate-access-key: ${{ secrets.TF_STATE_ACCESS_KEY }}
          tfstate-secret-key: ${{ secrets.TF_STATE_SECRET_KEY }}
          working-directory: ./terraform

      - name: Validate .tf files
        run: tofu validate
        working-directory: ./terraform

      - name: Terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -patch -- tofu plan -no-color -input=false
        working-directory: ./terraform
